package com.example.course_recommender.service;

import com.example.course_recommender.model.Author;
import com.example.course_recommender.repository.AuthorRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Optional;
import java.util.UUID;

/**
 * Service layer for managing Author-related business logic.
 * This class orchestrates data operations by interacting with the AuthorRepository.
 */
@Service // Marks this class as a Spring service component
public class AuthorService {

    private final AuthorRepository authorRepository;

    /**
     * Constructor for AuthorService. Spring injects AuthorRepository.
     *
     * @param authorRepository The AuthorRepository instance.
     */
    @Autowired
    public AuthorService(AuthorRepository authorRepository) {
        this.authorRepository = authorRepository;
    }

    /**
     * Adds a new author to the system.
     * Delegates to the repository for persistence.
     *
     * @param author The Author object to be added. Its ID will be generated by the database.
     * @return The saved Author object including its generated ID.
     */
    public Author addAuthor(Author author) {
        System.out.println("Attempting to add author: " + author.getName());
        // Add business validation here, e.g., check for unique email before saving
        return authorRepository.save(author);
    }

    /**
     * Updates an existing author.
     * Delegates to the repository for persistence.
     *
     * @param author The Author object with updated details. The ID must be present.
     * @return An Optional containing the updated Author if found, otherwise Optional.empty().
     */
    public Optional<Author> updateAuthor(Author author) {
        System.out.println("Attempting to update author with ID: " + author.getId());
        return authorRepository.update(author);
    }

    /**
     * Retrieves an author by its unique identifier.
     * Delegates to the repository for data retrieval.
     *
     * @param id The UUID of the author to retrieve.
     * @return An Optional containing the Author if found, otherwise Optional.empty().
     */
    public Optional<Author> viewAuthor(UUID id) {
        System.out.println("Attempting to view author with ID: " + id);
        return authorRepository.findById(id);
    }

    /**
     * Retrieves all available authors.
     * Delegates to the repository for data retrieval.
     *
     * @return A list of all Author objects.
     */
    public List<Author> getAllAuthors() {
        System.out.println("Attempting to retrieve all authors.");
        return authorRepository.findAll();
    }

    /**
     * Deletes an author by its unique identifier.
     * Delegates to the repository for data deletion.
     *
     * @param id The UUID of the author to delete.
     * @return true if the author was successfully deleted, false otherwise.
     */
    public boolean deleteAuthor(UUID id) {
        System.out.println("Attempting to delete author with ID: " + id);
        return authorRepository.deleteById(id);
    }

    /**
     * Retrieves all authors associated with a specific course.
     * Delegates to the repository.
     *
     * @param courseId The UUID of the course.
     * @return A list of Author objects associated with the given course.
     */
    public List<Author> getAuthorsByCourseId(UUID courseId) {
        return authorRepository.findAuthorsByCourseId(courseId);
    }
}
