package com.example.course_recommender.service;

import com.example.course_recommender.model.Course;
import com.example.course_recommender.repository.CourseRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Optional;
import java.util.UUID;

/**
 * Service layer for managing Course-related business logic.
 * This class orchestrates data operations by interacting with the CourseRepository.
 */
@Service // Marks this class as a Spring service component for component scanning
public class CourseService {

    private final CourseRepository courseRepository;

    /**
     * Constructor for CourseService. Spring will automatically
     * inject the CourseRepository implementation (CourseRepositoryImpl).
     *
     * @param courseRepository The CourseRepository instance.
     */
    @Autowired
    public CourseService(CourseRepository courseRepository) {
        this.courseRepository = courseRepository;
    }

    /**
     * Adds a new course to the system.
     * Delegates to the repository for persistence.
     *
     * @param course The Course object to be added. Its ID will be generated by the database.
     * @return The saved Course object including its generated ID.
     */
    public Course addCourse(Course course) {
        // Business logic or validation can be added here before saving
        System.out.println("Attempting to add course: " + course.getName());
        return courseRepository.save(course);
    }

    /**
     * Updates an existing course.
     * Delegates to the repository for persistence.
     *
     * @param course The Course object with updated details. The ID must be present.
     * @return An Optional containing the updated Course if found, otherwise Optional.empty().
     */
    public Optional<Course> updateCourse(Course course) {
        // Business logic or validation before update
        System.out.println("Attempting to update course with ID: " + course.getId());
        return courseRepository.update(course);
    }

    /**
     * Retrieves a course by its unique identifier.
     * Delegates to the repository for data retrieval.
     *
     * @param id The UUID of the course to retrieve.
     * @return An Optional containing the Course if found, otherwise Optional.empty().
     */
    public Optional<Course> viewCourse(UUID id) {
        System.out.println("Attempting to view course with ID: " + id);
        return courseRepository.findById(id);
    }

    /**
     * Retrieves all available courses.
     * Delegates to the repository for data retrieval.
     *
     * @return A list of all Course objects.
     */
    public List<Course> getAllCourses() {
        System.out.println("Attempting to retrieve all courses.");
        return courseRepository.findAll();
    }

    /**
     * Deletes a course by its unique identifier.
     * Delegates to the repository for data deletion.
     *
     * @param id The UUID of the course to delete.
     * @return true if the course was successfully deleted, false otherwise.
     */
    public boolean deleteCourse(UUID id) {
        System.out.println("Attempting to delete course with ID: " + id);
        return courseRepository.deleteById(id);
    }
}
