package com.example.course_recommender.mapper;

import com.example.course_recommender.dto.RatingDto;
import com.example.course_recommender.model.Rating;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;

import java.util.List;

/**
 * MapStruct Mapper for converting between Rating entity and RatingDto.
 * Uses Spring component model to be injectable.
 */
@Mapper(componentModel = "spring")
public interface RatingMapper {

    /**
     * Maps a Rating entity to a RatingDto.
     * The courseId is derived from the associated Course entity.
     *
     * @param rating The Rating entity.
     * @return The mapped RatingDto.
     */
    @Mapping(target = "courseId", source = "course.id")
    // Map course.id from entity to courseId in DTO
    RatingDto toDto(Rating rating);

    /**
     * Maps a RatingDto to a Rating entity.
     * The 'id' is ignored as it's typically generated by the database for new entities.
     * The 'course' entity is ignored and will be set separately in the service layer
     * by fetching the Course entity based on courseId.
     *
     * @param ratingDto The RatingDto.
     * @return The mapped Rating entity.
     */
    @Mapping(target = "id", ignore = true) // ID is generated by DB for new entities
    @Mapping(target = "course", ignore = true)
    // Course association is handled in service layer
    Rating toEntity(RatingDto ratingDto);

    /**
     * Updates an existing Rating entity from a RatingDto.
     * The 'id' and 'course' entity association are ignored during updates.
     *
     * @param ratingDto The RatingDto with updated values.
     * @param rating    The existing Rating entity to update.
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "course", ignore = true)
    void updateEntityFromDto(RatingDto ratingDto, @MappingTarget Rating rating);

    /**
     * Maps a list of Rating entities to a list of RatingDtos.
     *
     * @param ratings The list of Rating entities.
     * @return The list of mapped RatingDtos.
     */
    List<RatingDto> toDtoList(List<Rating> ratings);

    /**
     * Maps a list of RatingDtos to a list of Rating entities.
     *
     * @param ratingDtos The list of RatingDtos.
     * @return The list of mapped Rating entities.
     */
    List<Rating> toEntityList(List<RatingDto> ratingDtos);
}
