package com.example.course_recommender.mapper;

import com.example.course_recommender.dto.AssessmentDto;
import com.example.course_recommender.model.Assessment;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;

import java.util.List;

/**
 * MapStruct Mapper for converting between Assessment entity and AssessmentDto.
 * Uses Spring component model to be injectable.
 */
@Mapper(componentModel = "spring")
public interface AssessmentMapper {

    /**
     * Maps an Assessment entity to an AssessmentDto.
     * The courseId is derived from the associated Course entity.
     *
     * @param assessment The Assessment entity.
     * @return The mapped AssessmentDto.
     */
    @Mapping(target = "courseId", source = "course.id")
    // Map course.id from entity to courseId in DTO
    AssessmentDto toDto(Assessment assessment);

    /**
     * Maps an AssessmentDto to an Assessment entity.
     * The 'id' is ignored as it's typically generated by the database for new entities.
     * The 'course' entity is ignored and will be set separately in the service layer
     * by fetching the Course entity based on courseId.
     *
     * @param assessmentDto The AssessmentDto.
     * @return The mapped Assessment entity.
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "course", ignore = true)
    // Course association is handled in service layer
    Assessment toEntity(AssessmentDto assessmentDto);

    /**
     * Updates an existing Assessment entity from an AssessmentDto.
     * The 'id' and 'course' entity association are ignored during updates.
     *
     * @param assessmentDto The AssessmentDto with updated values.
     * @param assessment    The existing Assessment entity to update.
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "course", ignore = true)
    void updateEntityFromDto(AssessmentDto assessmentDto, @MappingTarget Assessment assessment);

    /**
     * Maps a list of Assessment entities to a list of AssessmentDtos.
     *
     * @param assessments The list of Assessment entities.
     * @return The list of mapped AssessmentDtos.
     */
    List<AssessmentDto> toDtoList(List<Assessment> assessments);

    /**
     * Maps a list of AssessmentDtos to a list of Assessment entities.
     *
     * @param assessmentDtos The list of AssessmentDtos.
     * @return The list of mapped Assessment entities.
     */
    List<Assessment> toEntityList(List<AssessmentDto> assessmentDtos);
}
